[env:esp32-c3-super-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Настройки загрузки
upload_speed = 921600
monitor_speed = 115200

; Дополнительные флаги компиляции
build_flags = 
    -D ARDUINO_ESP32C3_DEV

; Настройки мониторинга
monitor_filters = 
    default




