[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Настройки для Ethernet Shield W5500
lib_deps = 
    Ethernet2

; Настройки загрузки
upload_speed = 115200
monitor_speed = 9600

; Дополнительные флаги компиляции
build_flags = 
    -D ARDUINO_AVR_UNO 